language: erlang
dist: trusty
sudo: required
node_js: stable
env:
  - PATH=$HOME/purescript:$HOME/purerl:$HOME:$PATH PURS_VERSION=v0.13.6
otp_release:
  - 23.0
branches:
  # Only build master and tagged versions, i.e. not feature branches; feature
  # branches already get built after opening a pull request.
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
install:
  - curl -L https://github.com/purescript/purescript/releases/download/$PURS_VERSION/linux64.tar.gz -o $HOME/purescript.tar.gz
  - tar -xvf $HOME/purescript.tar.gz -C $HOME/
  - curl -L https://github.com/purescript/spago/releases/latest/download/linux.tar.gz -o $HOME/spago.tar.gz
  - tar -xvf $HOME/spago.tar.gz -C $HOME/
  - curl -L https://github.com/purerl/purerl/releases/latest/download/linux64.tar.gz -o $HOME/purerl.tar.gz
  - tar -xvf $HOME/purerl.tar.gz -C $HOME/
script:
  - make test
